# Generated by Django 6.1.1 on 2026-09-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('was_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai_assistant.aiconversation')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to='providers.providerprofile')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['rank'],
            },
        ),
    ]
